tap "caskroom/cask"
tap "homebrew/completions"

brew "cask"
brew "emacs", args: ["with-cocoa"]
brew "git"
brew "brew-cask-completion"
brew "bundler-completion"
brew "docker-completion"
brew "gem-completion"
brew "rails-completion"
brew "rake-completion"
brew "ruby-completion"
brew "spring-completion"
brew "vagrant-completion"

cask "docker"
cask "vagrant"
cask "chefdk"
cask "google-chrome"
cask "java"
cask "dropbox"
cask "freedome"
cask "iterm2"
